#!/usr/bin/env python3
"""
Train summary plot generator for run_id: v1
Generated by: train-sum agent
Date: 2026-04-03
"""

import json
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D

# ── Load metrics ─────────────────────────────────────────────────────────────
METRICS_PATH = "/Users/siyaoshao/auto-pinn-generation/simulator/pinn/checkpoints/run_v1_metrics.jsonl"

records = []
with open(METRICS_PATH, "r") as f:
    for line in f:
        line = line.strip()
        if line:
            records.append(json.loads(line))

# The file contains two runs. Use the second run (starts at index 6 where epoch resets to 1).
# Find where the second run begins.
second_run_start = None
for i in range(1, len(records)):
    if records[i]["epoch"] <= records[i-1]["epoch"]:
        second_run_start = i
        break

if second_run_start is not None:
    records = records[second_run_start:]

print(f"Using {len(records)} epoch records from the complete run.")
print(f"Epoch range: {records[0]['epoch']} -> {records[-1]['epoch']}")

epochs      = [r["epoch"]        for r in records]
val_data    = [r["val_data"]     for r in records]
val_ode     = [r["val_ode"]      for r in records]
val_vel     = [r["val_vel"]      for r in records]
val_phase   = [r["val_phase"]    for r in records]
val_total   = [r["val_total"]    for r in records]
phys_weight = [r["physics_weight"] for r in records]
lr_vals     = [r["lr"]           for r in records]

# λ weights
LAMBDA_ODE   = 1.3425e-4
LAMBDA_VEL   = 2.8691
LAMBDA_PHASE = 78.472

lw_ode   = [v * LAMBDA_ODE   for v in val_ode]
lw_vel   = [v * LAMBDA_VEL   for v in val_vel]
lw_phase = [v * LAMBDA_PHASE for v in val_phase]

# ── Identify best checkpoint and early stop ───────────────────────────────────
best_idx   = int(np.argmin(val_total))
best_epoch = epochs[best_idx]
best_loss  = val_total[best_idx]

# Early stop = last logged epoch
early_stop_epoch = epochs[-1]
total_epochs_run = len(records)

print(f"Best checkpoint: epoch={best_epoch}, val_total={best_loss:.6f}")
print(f"Early stop epoch: {early_stop_epoch}")
print(f"Physics weight at best: {phys_weight[best_idx]:.2f}")

# ── Build figure ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 14), facecolor="#0d0d0d")
gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)

DARK_BG   = "#0d0d0d"
PANEL_BG  = "#1a1a1a"
TEXT_COL  = "#e0e0e0"
GRID_COL  = "#333333"
BEST_COL  = "#00e5ff"
STOP_COL  = "#ff6b6b"

def style_ax(ax, title):
    ax.set_facecolor(PANEL_BG)
    for sp in ax.spines.values():
        sp.set_color("#444444")
    ax.tick_params(colors=TEXT_COL, labelsize=9)
    ax.xaxis.label.set_color(TEXT_COL)
    ax.yaxis.label.set_color(TEXT_COL)
    ax.set_title(title, color=TEXT_COL, fontsize=11, fontweight="bold", pad=8)
    ax.grid(True, color=GRID_COL, linewidth=0.5, linestyle="--", alpha=0.6)


# ── Panel 1 — Total val loss ──────────────────────────────────────────────────
ax1 = fig.add_subplot(gs[0, 0])
style_ax(ax1, "Total Validation Loss")
ax1.plot(epochs, val_total, color="#4fc3f7", linewidth=1.8, label="val_total")

# Best checkpoint vertical dashed line
ax1.axvline(best_epoch, color=BEST_COL, linestyle="--", linewidth=1.4, alpha=0.9)
ax1.annotate(
    f"best: epoch={best_epoch}\nloss={best_loss:.4f}",
    xy=(best_epoch, best_loss),
    xytext=(best_epoch + max(1, len(epochs)*0.08), best_loss + (max(val_total) - min(val_total)) * 0.06),
    color=BEST_COL, fontsize=8,
    arrowprops=dict(arrowstyle="->", color=BEST_COL, lw=1.0),
)

# Early stop vertical dotted line
ax1.axvline(early_stop_epoch, color=STOP_COL, linestyle=":", linewidth=1.4, alpha=0.9)
ax1.annotate(
    "early stop",
    xy=(early_stop_epoch, val_total[-1]),
    xytext=(early_stop_epoch - max(1, len(epochs)*0.15), val_total[-1] + (max(val_total) - min(val_total)) * 0.10),
    color=STOP_COL, fontsize=8,
    arrowprops=dict(arrowstyle="->", color=STOP_COL, lw=1.0),
)

ax1.set_xlabel("Epoch")
ax1.set_ylabel("val_total")
ax1.legend(facecolor=PANEL_BG, labelcolor=TEXT_COL, fontsize=8, framealpha=0.7)


# ── Panel 2 — Physics loss components ────────────────────────────────────────
ax2 = fig.add_subplot(gs[0, 1])
style_ax(ax2, "Physics Loss Components (λ-weighted)")
ax2.plot(epochs, val_data,  color="#4fc3f7", linewidth=1.5, label="val_data")
ax2.plot(epochs, lw_ode,    color="#f48fb1", linewidth=1.5, label=f"λ·val_ode  (λ={LAMBDA_ODE:.4e})")
ax2.plot(epochs, lw_vel,    color="#a5d6a7", linewidth=1.5, label=f"λ·val_vel  (λ={LAMBDA_VEL})")
ax2.plot(epochs, lw_phase,  color="#ffe082", linewidth=1.5, label=f"λ·val_phase (λ={LAMBDA_PHASE})")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Loss (λ-weighted)")
ax2.legend(facecolor=PANEL_BG, labelcolor=TEXT_COL, fontsize=7.5, framealpha=0.7)


# ── Panel 3 — Physics ramp + LR ──────────────────────────────────────────────
ax3 = fig.add_subplot(gs[1, 0])
style_ax(ax3, "Physics Ramp & Learning Rate")

color_pw = "#ce93d8"
color_lr = "#80cbc4"

ax3.plot(epochs, phys_weight, color=color_pw, linewidth=1.8, label="physics_weight", drawstyle="steps-post")
ax3.set_xlabel("Epoch")
ax3.set_ylabel("physics_weight", color=color_pw)
ax3.tick_params(axis="y", labelcolor=color_pw)
ax3.set_ylim(-0.05, 1.15)

# Warmup completion line at epoch 100
ax3.axvline(100, color="#ffcc02", linestyle="-.", linewidth=1.2, alpha=0.85)
ax3.text(102, 0.55, "warmup\ncomplete\n(epoch 100)", color="#ffcc02", fontsize=7.5, va="center")

ax3r = ax3.twinx()
ax3r.set_facecolor(PANEL_BG)
ax3r.plot(epochs, lr_vals, color=color_lr, linewidth=1.4, linestyle="--", label="lr")
ax3r.set_ylabel("Learning Rate", color=color_lr)
ax3r.tick_params(axis="y", labelcolor=color_lr, labelsize=8)
for sp in ax3r.spines.values():
    sp.set_color("#444444")

lines_a = [Line2D([0],[0], color=color_pw, lw=1.8, label="physics_weight", drawstyle="steps-post"),
           Line2D([0],[0], color=color_lr, lw=1.4, ls="--", label="lr")]
ax3.legend(handles=lines_a, facecolor=PANEL_BG, labelcolor=TEXT_COL, fontsize=8, framealpha=0.7)


# ── Panel 4 — Summary table ───────────────────────────────────────────────────
ax4 = fig.add_subplot(gs[1, 1])
ax4.set_facecolor(PANEL_BG)
ax4.axis("off")
ax4.set_title("Training Summary — run_id: v1", color=TEXT_COL, fontsize=11, fontweight="bold", pad=8)

table_data = [
    ["Metric",                    "Value",                               "Epoch"],
    ["Best val loss",             f"{best_loss:.6f}",                    str(best_epoch)],
    ["Val data loss at best",     f"{val_data[best_idx]:.6f}",           "—"],
    ["Val ODE loss at best",      f"{val_ode[best_idx]:.4f}",            "—"],
    ["Val vel loss at best",      f"{val_vel[best_idx]:.6f}",            "—"],
    ["Val phase loss at best",    f"{val_phase[best_idx]:.6f}",          "—"],
    ["Early stop epoch",          str(early_stop_epoch),                 "—"],
    ["Total epochs run",          str(total_epochs_run),                 "—"],
    ["Physics weight at best",    f"{phys_weight[best_idx]:.2f}",        "—"],
]

tbl = ax4.table(
    cellText=table_data[1:],
    colLabels=table_data[0],
    cellLoc="center",
    loc="center",
    bbox=[0.0, 0.0, 1.0, 1.0],
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(9)

header_color = "#263238"
row_colors   = ["#1e2a2e", "#1a2428"]
text_c       = "#e0e0e0"

for (row, col), cell in tbl.get_celld().items():
    cell.set_edgecolor("#444444")
    if row == 0:
        cell.set_facecolor(header_color)
        cell.set_text_props(color="#80cbc4", fontweight="bold")
    else:
        cell.set_facecolor(row_colors[(row - 1) % 2])
        cell.set_text_props(color=text_c)


# ── Save ──────────────────────────────────────────────────────────────────────
OUT_DIR = "/Users/siyaoshao/auto-pinn-generation/docs/executive_branch_document/plots/pinn_training"
PNG_PATH = os.path.join(OUT_DIR, "train_summary_v1.png")
fig.suptitle("PINN Training Run — v1", color=TEXT_COL, fontsize=14, fontweight="bold", y=0.98)
plt.savefig(PNG_PATH, dpi=150, bbox_inches="tight", facecolor=DARK_BG)
plt.close()
print(f"Saved plot: {PNG_PATH}")

# ── Markdown summary ──────────────────────────────────────────────────────────
lw_ode_best   = val_ode[best_idx]   * LAMBDA_ODE
lw_vel_best   = val_vel[best_idx]   * LAMBDA_VEL
lw_phase_best = val_phase[best_idx] * LAMBDA_PHASE

MD_PATH = os.path.join(OUT_DIR, "train_summary_v1.md")
md_content = f"""# Training Summary — run_id: v1
**Generated by:** train-sum agent
**Date:** 2026-04-03

## Key Results
| Metric | Value |
|---|---|
| Best val loss | {best_loss:.6f} |
| Best epoch | {best_epoch} |
| Physics weight at best epoch | {phys_weight[best_idx]:.2f} |
| Early stop epoch | {early_stop_epoch} |
| Total epochs run | {total_epochs_run} |

## Observation
The best checkpoint was saved at epoch {best_epoch} when physics_weight={phys_weight[best_idx]:.2f}.
Val loss increased after full physics weighting (epoch 100+).
This pattern requires human review before proceeding to pinn-validator.

## Loss at Best Checkpoint
| Component | Raw value | λ-weighted |
|---|---|---|
| data | {val_data[best_idx]:.4f} | {val_data[best_idx]:.4f} (no λ) |
| L_ODE | {val_ode[best_idx]:.4f} | {lw_ode_best:.6f} |
| L_vel | {val_vel[best_idx]:.4f} | {lw_vel_best:.6f} |
| L_phase | {val_phase[best_idx]:.6f} | {lw_phase_best:.6f} |

## Plot
See train_summary_v1.png in this directory.
"""

with open(MD_PATH, "w") as f:
    f.write(md_content)
print(f"Saved markdown: {MD_PATH}")

# ── Final print ───────────────────────────────────────────────────────────────
print()
print("═══════════════════════════════════════")
print("TRAIN SUMMARY COMPLETE — run_id: v1")
print(f"Plot:    docs/executive_branch_document/plots/pinn_training/train_summary_v1.png")
print(f"Summary: docs/executive_branch_document/plots/pinn_training/train_summary_v1.md")
print()
print(f"KEY OBSERVATION: Best checkpoint at epoch {best_epoch} (physics_weight={phys_weight[best_idx]:.2f}).")
print(f"Val loss increased once full physics weighting applied at epoch 100.")
print("HUMAN REVIEW REQUIRED before pinn-validator proceeds.")
print("═══════════════════════════════════════")
