"""
PINN Physics Loss v3 — written by loss-setter agent, 2026-04-19.
Bill reference: bill_physics_loss_v3.md
Amendment: Amendment 21 (Data-Physics Alignment Rule, ratified 2026-04-18)

Four physics loss terms, each algebraically traced to at least one
of the three walking primitives (Article I, Amendment 17).

Loss terms:
  L_gyy_pulse  — gy waveform constraint (half-sine push-off + stance/swing)
                 (traces to: cadence_spm, step_length_m, slope_deg)
  L_az_gravity — az DC baseline constraint
                 (traces to: vertical_oscillation_cm, cadence_spm)
  L_vel        — Horizontal velocity constraint
                 (traces to: cadence_spm, step_length_m)
  L_phase      — Stance/swing timing constraint
                 (traces to: cadence_spm via step_period_s)

Replaces: L_ODE (spring oscillator on az) — removed per Amendment 21.
  The spring oscillator ODE cannot converge to the half-sine push-off waveform
  generated by walker_model.py. val_ode diverged 36->58 over 100 epochs (v3 run).

All lambda weights are injected at runtime from train_config.json.
No hardcoded weight values in this file (Amendment 17).

AUTOGRAD NOTE: ax_pred must have requires_grad=True for L_vel (torch.trapezoid
on live graph). gy_pred and az_pred do not require autograd for the new terms.

Lambda reference values (bill_loss_recalibration_v1.md, 2026-04-19 — PENDING RATIFICATION):
  lambda_gyy   = 3.651e-04  (target weighted = 1.0; reference L_gyy = 2739 dps^2 at v4 plateau)
  lambda_az    = 9.443      (target weighted = 1.0; reference L_az  = 0.1059 (m/s^2)^2 at v4 plateau)
  lambda_vel   = 1.126      (target weighted = 1.0; reference L_vel = 0.8880 m^2/s^2 at v4 plateau)
  lambda_phase = 1069       (target weighted = 0.1; soft sign constraint, already converged at v4)
  Prior values (bill_physics_loss_v3.md):
  lambda_gyy   = 2.994e-05  lambda_az = 6.054e-03  lambda_vel = 4.908  lambda_phase = 73.625
"""

import math
import torch
import torch.nn as nn

G = 9.81  # m/s²


def _build_gy_target(
    t:             torch.Tensor,   # (N,) normalised step time [0,1]
    peak_angvel:   torch.Tensor,   # (N,) push-off peak [dps]
    stance_frac:   torch.Tensor,   # (N,) [dimensionless]
) -> torch.Tensor:
    """
    Reconstruct the walker_model.py gy waveform from primitives.

    Derivation (walker_model.py lines 253-278):
      Stance phase normalised: phase = t / stance_frac  (maps [0, stance_frac] -> [0,1])
      - phase [0.00, 0.10]:  gy = -peak x 0.35 x exp(-phase x 30)  heel-strike dorsiflexion
      - phase [0.10, 0.18]:  gy = +peak x 0.05 x sin(pi x rebound)  ankle rocker rebound
      - phase [0.18, 0.75]:  gy = -peak x 0.20 x ramp               mid-stance dorsiflexion
      - phase [0.75, 1.00]:  gy = +peak x sin(pi x push_phase)       HALF-SINE PUSH-OFF PULSE
      Swing phase normalised: phase = (t - stance_frac) / (1 - stance_frac)
      - swing:               gy = -peak x 0.25 x sin(pi x phase)     foot deceleration

    peak_angvel traces to cadence_spm and step_length_m via:
      walking_speed_ms = (cadence_spm / 60) x step_length_m
      peak_angvel_dps  = (100 + 65 x walking_speed_ms) x slope_factor   (Article I)
    """
    eps = 1e-6
    sf = torch.clamp(stance_frac, min=eps, max=1.0 - eps)

    in_stance = (t <= sf).float()
    phase_s = torch.clamp(t / sf, min=0.0, max=1.0)
    phase_w = torch.clamp((t - sf) / (1.0 - sf), min=0.0, max=1.0)

    # Heel-strike exponential decay [0.00, 0.10]
    gy_hs = -peak_angvel * 0.35 * torch.exp(-phase_s * 30.0)

    # Ankle rocker rebound [0.10, 0.18]
    rebound = torch.clamp((phase_s - 0.10) / 0.08, min=0.0, max=1.0)
    gy_rb = peak_angvel * 0.05 * torch.sin(math.pi * rebound)

    # Mid-stance dorsiflexion ramp [0.18, 0.75]
    ramp = torch.clamp((phase_s - 0.18) / (0.72 - 0.18), min=0.0, max=1.0)
    gy_ms = -peak_angvel * 0.20 * ramp

    # Push-off half-sine pulse [0.75, 1.00]
    push = torch.clamp((phase_s - 0.75) / 0.25, min=0.0, max=1.0)
    gy_push = peak_angvel * torch.sin(math.pi * push)

    m_hs   = ((phase_s >= 0.00) & (phase_s < 0.10)).float()
    m_rb   = ((phase_s >= 0.10) & (phase_s < 0.18)).float()
    m_ms   = ((phase_s >= 0.18) & (phase_s < 0.75)).float()
    m_push = (phase_s >= 0.75).float()

    gy_stance = gy_hs * m_hs + gy_rb * m_rb + gy_ms * m_ms + gy_push * m_push
    gy_swing  = -peak_angvel * 0.25 * torch.sin(math.pi * phase_w)

    return gy_stance * in_stance + gy_swing * (1.0 - in_stance)


class PhysicsLoss(nn.Module):
    """
    Computes the four physics loss terms for PINN training (v3).

    Weights passed at call time from train_config.json (Amendment 17).
    """

    def __init__(self):
        super().__init__()

    # ─────────────────────────────────────────────────────────────────
    # L_gyy_pulse — gy Waveform Constraint  (replaces L_ODE)
    # ─────────────────────────────────────────────────────────────────
    def l_gyy_pulse(
        self,
        gy_pred:       torch.Tensor,   # (N,) predicted gyr_y [dps]
        t:             torch.Tensor,   # (N,) normalised step time [0,1]
        cadence_spm:   torch.Tensor,   # (N,)
        step_length_m: torch.Tensor,   # (N,)
        slope_deg:     torch.Tensor,   # (N,)
        stance_frac:   torch.Tensor,   # (N,)
        terrain_int:   torch.Tensor,   # (N,)  0=flat,1=slope,2=stairs
    ) -> torch.Tensor:
        """
        MSE between gy_pred and the primitive-derived composite waveform.

        Amplitude derivation (Article I trace):
          walking_speed_ms = (cadence_spm / 60) x step_length_m
          slope_factor     = 1 + 0.4 x sin(slope_deg x pi/180)
          peak_angvel_dps  = (100 + 65 x walking_speed_ms) x slope_factor
          stairs_factor    = 1.5 if terrain_int == 2 else 1.0
                             (walker_model.py __post_init__ line 92 — extra
                             plantarflexion to clear the riser)

        Shape: _build_gy_target() uses exact mathematical forms from
               walker_model.py lines 253-278 (Amendment 21 compliance).

        lambda_gyy = 3.651e-04  (bill_loss_recalibration_v1 — PENDING RATIFICATION)
          reference: L_gyy plateau = 2739 dps^2 (v4 run, epochs 1-200)
          prior:     lambda_gyy = 2.994e-05 (bill_physics_loss_v3)
        """
        slope_rad     = slope_deg * (math.pi / 180.0)
        slope_factor  = 1.0 + 0.4 * torch.sin(slope_rad)
        v_walk        = (cadence_spm / 60.0) * step_length_m
        stairs_factor = torch.where(terrain_int >= 1.5, torch.full_like(v_walk, 1.5), torch.ones_like(v_walk))
        peak_angvel   = (100.0 + 65.0 * v_walk) * slope_factor * stairs_factor

        gy_target = _build_gy_target(t, peak_angvel, stance_frac)
        return torch.mean((gy_pred - gy_target) ** 2)

    # ─────────────────────────────────────────────────────────────────
    # L_az_gravity — az DC Baseline Constraint  (replaces L_ODE)
    # ─────────────────────────────────────────────────────────────────
    def l_az_gravity(
        self,
        az_pred:       torch.Tensor,   # (N,) predicted acc_z [m/s^2]
        cadence_spm:   torch.Tensor,   # (N,)
        vert_osc_cm:   torch.Tensor,   # (N,)
        slope_deg:     torch.Tensor,   # (N,)
        t_steps:       int = 208,
    ) -> torch.Tensor:
        """
        Per-profile mean az_pred must equal theoretical DC baseline.

        Derivation (Article I trace):
          az_dc = G x cos(slope_rad)
                + (vert_osc_cm / 100) x (cadence_spm / 60)^2 x 2pi^2

          First term:  gravity projection onto sensor z-axis [traces to slope_deg]
          Second term: peak CoM vertical acceleration (SHM, time-averaged)
                       [traces to vertical_oscillation_cm + cadence_spm]

        lambda_az = 9.443  (bill_loss_recalibration_v1 — PENDING RATIFICATION)
          reference: L_az plateau = 0.1059 (m/s^2)^2 (v4 run, epochs 1-200)
          prior:     lambda_az = 6.054e-03 (bill_physics_loss_v3)
        """
        slope_rad = slope_deg * (math.pi / 180.0)
        omega     = 2.0 * math.pi * cadence_spm / 60.0
        az_dc     = G * torch.cos(slope_rad) \
                  + (vert_osc_cm / 100.0) * omega ** 2 / (2.0 * math.pi ** 2)

        B          = az_pred.shape[0] // t_steps
        az_mat     = az_pred.reshape(B, t_steps)
        az_dc_mat  = az_dc.reshape(B, t_steps)[:, 0]
        mean_az    = az_mat.mean(dim=1)
        return torch.mean((mean_az - az_dc_mat) ** 2)

    # ─────────────────────────────────────────────────────────────────
    # L_vel — Horizontal Velocity Constraint  (unchanged from v2)
    # ─────────────────────────────────────────────────────────────────
    def l_vel(
        self,
        ax_pred:       torch.Tensor,   # (N,) predicted horizontal accel [m/s^2]
        cadence_spm:   torch.Tensor,
        step_length_m: torch.Tensor,
        step_period_s: torch.Tensor,
    ) -> torch.Tensor:
        """
        v_x = (cadence_spm / 60) x step_length_m
        v_x_pred = mean(ax_pred) x step_period_s
        Loss: mean((v_x_pred - v_x_expected)^2)

        AUTOGRAD REQUIREMENT: ax_pred must have requires_grad=True.

        lambda_vel = 1.126  (bill_loss_recalibration_v1 — PENDING RATIFICATION)
          reference: L_vel plateau = 0.8880 m^2/s^2 (v4 run, epochs 1-200)
          prior:     lambda_vel = 4.908 (bill_train_config_v4)
        """
        assert ax_pred.requires_grad, (
            "L_vel autograd violation: ax_pred.requires_grad is False."
        )
        v_x_expected = (cadence_spm / 60.0) * step_length_m
        v_x_pred     = torch.mean(ax_pred) * step_period_s
        return torch.mean((v_x_pred - v_x_expected) ** 2)

    # ─────────────────────────────────────────────────────────────────
    # L_phase — Stance/Swing Timing Constraint  (unchanged from v2)
    # ─────────────────────────────────────────────────────────────────
    def l_phase(
        self,
        gy_pred:     torch.Tensor,
        t:           torch.Tensor,
        stance_frac: torch.Tensor,
    ) -> torch.Tensor:
        """
        Soft constraint: mean(gy_pred) during stance < 0.
        Boundary: gy_pred near t=stance_frac ~ 0 (lift-off).
        [traces to cadence_spm via stance_frac]

        lambda_phase = 1069  (bill_loss_recalibration_v1 — PENDING RATIFICATION)
          reference: L_phase plateau = 9.356e-05 (v4 run, epochs 1-200)
          target weighted = 0.1 (already converged; soft constraint only)
          prior:     lambda_phase = 73.625 (bill_train_config_v4)
        """
        stance_mask      = (t < stance_frac).float()
        n_stance         = stance_mask.sum() + 1e-6
        mean_gy_stance   = (gy_pred * stance_mask).sum() / n_stance
        stance_violation = torch.clamp(mean_gy_stance, min=0.0) ** 2

        boundary_mask    = (torch.abs(t - stance_frac) < 0.05).float()
        n_boundary       = boundary_mask.sum() + 1e-6
        mean_gy_boundary = (gy_pred * boundary_mask).sum() / n_boundary
        boundary_loss    = mean_gy_boundary ** 2

        return stance_violation + 0.5 * boundary_loss

    # ─────────────────────────────────────────────────────────────────
    # Total Loss
    # ─────────────────────────────────────────────────────────────────
    def total_loss(
        self,
        pred:                torch.Tensor,   # (N, 6)
        t:                   torch.Tensor,   # (N,)
        cadence_spm:         torch.Tensor,
        step_length_m:       torch.Tensor,
        vert_osc_cm:         torch.Tensor,
        stance_frac:         torch.Tensor,
        step_period_s:       torch.Tensor,
        slope_deg:           torch.Tensor,   # new in v3
        terrain_int:         torch.Tensor,   # new in v3 (stairs 1.5x fix)
        lambda_gyy:          float,          # new in v3 (replaces lambda_ode)
        lambda_az:           float,          # new in v3
        lambda_vel:          float,
        lambda_phase:        float,
        physics_weight_ramp: float = 1.0,   # Amendment 20
        t_steps:             int   = 208,
    ) -> dict:
        """
        Returns dict: l_gyy, l_az, l_vel, l_phase, physics
        physics_weight_ramp: 0->1 linear ramp during warmup (Amendment 20)
        """
        ax_pred = pred[:, 0]
        az_pred = pred[:, 2]
        gy_pred = pred[:, 4]

        loss_gyy   = self.l_gyy_pulse(gy_pred, t, cadence_spm, step_length_m,
                                       slope_deg, stance_frac, terrain_int)
        loss_az    = self.l_az_gravity(az_pred, cadence_spm, vert_osc_cm,
                                        slope_deg, t_steps=t_steps)
        loss_vel   = self.l_vel(ax_pred, cadence_spm, step_length_m, step_period_s)
        loss_phase = self.l_phase(gy_pred, t, stance_frac)

        physics_total = physics_weight_ramp * (
            lambda_gyy   * loss_gyy   +
            lambda_az    * loss_az    +
            lambda_vel   * loss_vel   +
            lambda_phase * loss_phase
        )

        return {
            "l_gyy":   loss_gyy,
            "l_az":    loss_az,
            "l_vel":   loss_vel,
            "l_phase": loss_phase,
            "physics": physics_total,
        }
